### ISSUE TITLE
Editor issue

### ISSUE THREAD

**Issue by douggrubba** [ericlbarnes/wardrobe#1]
@ericbarnes just something to keep an eye on.  But I basically updated everything, repo, back-end and front-end, reran `grunt`, and served the site and everything looks fine but it appeared to break the editor for new and editing posts.

Didn't have much time to look into it, time to make dinner.  :)

**Comment by ericlbarnes** [comment]
working fine for me locally. You getting any errors in console? Also you using chrome?

**Comment by taylorotwell** [comment]
+1

**Comment by douggrubba** [comment]
Hrm, no errors and chrome.  I'll give it another go then.

**Comment by ericlbarnes** [comment]
maybe just git pull and not running grunt since I am pushing those.

**Comment by taylorotwell** [comment]
+1

**Comment by douggrubba** [comment]
Thanks for the input.

I did a fresh install on a diff machine and went back through with no issues.  Editor is showing up just fine.  Not really sure what happened.  Will report back if I can figure out how I caused it.

My guess is something in app.js got funky even though it wasn't throwing anything in the console.
