### ISSUE TITLE
Paths/urls relative to the root

### ISSUE THREAD

**Issue by martindilling** [ericlbarnes/wardrobe#11]
Not entirely sure if it's just me who does something wrong, but all the urls on links, buttons and assets is relative to the root. That makes it quite hard to install this in a subfolder, fx www.mysite.com/blog/ :(

In the html stuff I could put in {{ url('path/to/stuff') }} where needed, but I have no idea how to fix it in the backbone part, so I couldn't get it to work with posting new articles :/

**Comment by ericlbarnes** [comment]
Ah yeah. Failure on my part for not thinking about subfolders. I will get this fixed tonight. 

## 

Eric Barnes
@ericlbarnes

On June 17, 2013 at 9:36:40 AM, Martin Dilling-Hansen (notifications@github.com) wrote:
Not entirely sure if it's just me who does something wrong, but all the urls on links, buttons and assets is relative to the root. That makes it quite hard to install this in a subfolder, fx www.mysite.com/blog/ :(
In the html stuff I could put in {{ url('path/to/stuff') }} where needed, but I have no idea how to fix it in the backbone part, so I couldn't get it to work with posting new articles :/
— Reply to this email directly or view it on GitHub.￼

**Comment by martindilling** [comment]
looking forward to testing it after my exams ;)

**Comment by bjrnblm** [comment]
The install procedure needs the url prefix as well, its still redirecting everything to root /install now.
