### ISSUE TITLE
Fresh install is erroring.

### ISSUE THREAD

**Issue by ellisio** [ericlbarnes/wardrobe#15]
When doing a fresh install I am getting the following error:

```
composer install
PHP Fatal error:  include(): Cannot redeclare class symfony\component\process\process in phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php on line 185

Fatal error: include(): Cannot redeclare class symfony\component\process\process in phar:///usr/local/bin/composer/vendor/composer/ClassLoader.php on line 185
zend_mm_heap corrupted
```

Composer version: `d498e73363f8dae5b9984bf84ff2a2ca27240925`

Regards

**Comment by ellisio** [comment]
It appears that doing the following works:

```
cd project-dir
cp /usr/local/bin/composer composer.phar
php composer.phar install
```

Odd...

**Comment by ericlbarnes** [comment]
Maybe your global composer is out of date? Can't say I have seen this before.

**Comment by rtablada** [comment]
Try running composer selfupdate

**Comment by ellisio** [comment]
I **just** installed composer before doing this. Maybe it's a bug in Composer itself. I'll try self-updating tonight and see if they fixed this.

**Comment by ericlbarnes** [comment]
I wanted to follow back up with this. Did you ever get it going? Or give up :(

**Comment by ellisio** [comment]
Hey @ericbarnes -- I just went to run the "global install" of Composer again and I got a warning about `apc.enable_cli` saying it needed to be set to `Off`. I did not get this the first time when installing Composer globally. I set this and everything installed smoothly this time. Weird.
