### ISSUE TITLE
Add wardrobe as a package to packagist

### ISSUE THREAD

**Issue by Kindari** [ericlbarnes/wardrobe#16]
Biggest benefit from this, while others could be argued, is that you would be able to do:

```
composer create-project ericbarnes/wardrobe
```

And be done with installing.

**Comment by ericlbarnes** [comment]
Maybe I am looking this wrong but wouldn't this cause more headaches than it would solve? Meaning it would make editing themes and such harder.

**Comment by rtablada** [comment]
I don't see how this changes anything for themes? It is the same as git clone except that it does not setup everything as a git repo. Therefore I suggest that this shouldn't really be implemented until wardrobe is stable.

**Comment by ericlbarnes** [comment]
Yeah I guess I need to research this more. I was thinking it would throw everything in vendor/ just like other packages. I haven't used any that are real apps.

**Comment by rtablada** [comment]
Once you create a stable project package it can be created with composer project-create which essentially pulls the zip, unpacks it, then runs composer install (and you can add commands after too). You can see this in rtablada/test-shell package

Have a blessed day,
Ryan Tablada
ryan.tablada@gmail.com

**Comment by Kindari** [comment]
This is also the recommended way to install laravel: http://laravel.com/docs/quick#installation

Furthermore you _can_ add `--prefer-source` to get the git repo itself instead of the zip file.

```
composer create-project --prefer-source laravel/laravel
```

Is the same thing as 

```
git clone git@github.com:laravel/laravel.git
cd laravel
composer install
```

Omiting `--prefer-source` is essentially wget'ing the zip file.

Lastly at the end of installing the project with the `--prefer-source` flag, it asks you if you want to remove the history.

```
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? n
```

**Comment by jondavidjohn** [comment]
Could you put the wardrobe core files in a packagist package, but have it look out into the project for additional themes and config files?  Seems like this could allow better separation of Wardrobes' "app" code and the intended user "theme" code.

Ignore me if this doesn't make sense, I'm a complete laravel and composer beginner.

**Comment by rtablada** [comment]
I am playing with the ability to move the routes and controllers all into a nice package so that it can be installed in any Laravel (and possibly other) Framework. There are some workarounds that need to be discussed to make this happen (it will require a few more commands and stuff though...).

**Comment by ericlbarnes** [comment]
I started experimenting with this last night and I will be moving it over as I have time. Basically it will be set up similar to laravel one repo for the app and another for the structure. That way to get the latest you can just composer update. 

For the assets it looks like I can use `php artisan asset:publish` in the composer.json events.

**Comment by rtablada** [comment]
Eric, if it helps you out, I can help you migrate it to be a package. I was also thinking of wrapping it up with a route group that grabs its properties from configuration so that it is a bit easier to manage subdomains, prefixes, etc within existing laravel projects.
—

**Comment by rtablada** [comment]
@ericbarnes I am going to start looking at moving this over to a package so it will integrate nicely with existing Laravel projects.

**Comment by seblavoie** [comment]
@rtablada :+1: That would be a really cool addition to the project. Being able to use it as a part of a bigger project would be nice for a lot of users.

**Comment by rtablada** [comment]
I'm experimenting on how much abstraction/configuration should be included and how to split the project up.

**Comment by seblavoie** [comment]
I’m more of a front-end guy but let me know if I can help. Otherwise cheers for the great work.

**Comment by rtablada** [comment]
I'm thinking migrate first to wardrobe/core and wardrobe/wardrobe. Then pulling components apart such as admin, templating, etc.

**Comment by ericlbarnes** [comment]
Going ahead and closing this sense it's almost complete at:  
https://github.com/wardrobecms
