### ISSUE TITLE
Icons do not display in 127.0.0.1

### ISSUE THREAD

**Issue by philwinkle** [ericlbarnes/wardrobe#17]
Icons are not displaying in toolbars when hosting from php built-in server:

![image](https://f.cloud.github.com/assets/589550/665137/70189130-d795-11e2-8c4d-aa65d101ffcb.png)

**Comment by ericlbarnes** [comment]
What browser are you using for this? Also any errors in console?

**Comment by philwinkle** [comment]
Chrome Version 27.0.1453.110. No errors in console.

**Comment by dhrrgn** [comment]
What is the exact command you are starting the server with?

**Comment by philwinkle** [comment]
From within /public:

`php -S 127.0.0.1:8080 router.php`

router.php is a custom router intended to mimic the htaccess:

``` php
<?php

 if (file_exists(".".$_SERVER["REQUEST_URI"]))  {
      return false;
  } else {
      include_once 'index.php';
  }

```

**Comment by ericlbarnes** [comment]
Pretty sure it's your router file. I tried duplicating and loading the font failed:
http://127.0.0.1:8080/admin/font/fontawesome-webfont.woff?v=3.1.0

**Comment by philwinkle** [comment]
:thumbsup: Disregard - the querystring param on the font file is what was causing my issue. Apologies.

**Comment by ericlbarnes** [comment]
Okay, cool and thanks for the follow up.
