### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by clarkeash** [ericlbarnes/wardrobe#20]
add a code icon to the toolbar. (and tab in automatically)
at the bottom it gives a word count (it actually counts characters not words)
It would be nice to have a place to find themes.

Great job though :smile:

**Comment by ericlbarnes** [comment]
???

**Comment by clarkeash** [comment]
Sorry, hit enter when typing the title.

**Comment by rtablada** [comment]
As far as themes and plugs go, I am looking to implement a system in the future. A place to have a list of supported plugs and themes.

**Comment by ericlbarnes** [comment]
Good ideas. I will get those first two fixed/added soon. Maybe tonight.

@rtablada did you say you may have something in the works as for a third party system?

**Comment by clarkeash** [comment]
Great. I will let you know if I think of anything else.

**Comment by rtablada** [comment]
Yeah. I've got a huge client project, but I'm looking to create a plugin/theme site on getwardrobeblog.com

**Comment by ericlbarnes** [comment]
Closing this as I think building the other will take some time.
