### ISSUE TITLE
View [themes.default.index] not found

### ISSUE THREAD

**Issue by wietseva** [ericlbarnes/wardrobe#22]
I get an "InvalidArgumentException
View [themes.default.index] not found" when I try to open index after install. 
"mysite.com/wardrobe" works fine

[edit] 
solved the issue by copying the themes folder from public to views

**Comment by dwightwatson** [comment]
I don't think this should be closed - this is a bug in the app that needs to be fixed.

**Comment by ericlbarnes** [comment]
@dwightwatson Did you get this same error? 

Inside the config/view.php I am setting an array to search for view files which should default to your public/ folder. 
https://github.com/ericbarnes/wardrobe/blob/master/app/config/view.php#L16

A few questions to help me figure out what is going on: 
1. What operating system are you on? 
2. Is wardrobe installed in a sub folder? 
3. Are you using a different environment? Such as app/config/production/view.php

**Comment by dwightwatson** [comment]
Yeah I did, I cloned the repo tonight onto a Media Temple (gs), it's on a root level domain and using the standard environment. Was literally an out-of-the-box install, I can try again to double check it occurs again?

**Comment by ericlbarnes** [comment]
Okay. I will also look more in depth tonight. I feel like it has to be an issue with the way that path is set. 

When the reporter closed it I figured it was just a invalid issue. Missed the part where they moved them into views/ directory. 

-- Eric Barnes

**Comment by ericlbarnes** [comment]
Commit https://github.com/ericbarnes/wardrobe/commit/d2a96d70821f8e2f7a23a84f2ff005ca6754d87a should fix this. Please let me know if that isn't the case.

**Comment by dwightwatson** [comment]
Yeah, that's the one. Was an issue on Media Temple (gs) hosting because the public folder is meant to be `html` instead of `public`. Thanks for the quick turnaround!
