### ISSUE TITLE
ReferenceError: event is not defined

### ISSUE THREAD

**Issue by alphabraga** [ericlbarnes/wardrobe#23]
I was trying to create a post in admin area but i receive an error message: "The slug field is required". Wen i open the firebug console  i see "ReferenceError: event is not defined". 

The error happens in Firefox 21.0 for Ubuntu, when i try to create a post in Chrome 27 runs perfectly.

**Comment by ericlbarnes** [comment]
Did the title entered have weird characters or anything? 

## 

Eric Barnes
On June 20, 2013 at 10:58:10 AM, Alfredo Braga (notifications@github.com) wrote:
I was trying to create a post in admin area but i receive an error message: "The slug field is required". Wen i open the firebug console i see "ReferenceError: event is not defined".
The error happens in Firefox 21.0 for Ubuntu, when i try to create a post in Chrome 27 runs perfectly.
— Reply to this email directly or view it on GitHub.￼
