### ISSUE TITLE
Feature Request: Config file for themes

### ISSUE THREAD

**Issue by koomai** [ericlbarnes/wardrobe#31]
It would be great if a config file could be included in the themes folder. This would make it easier to add theme-specific options. Thinking of a more elegant solution to straight up including a php file at the top of the layout file.

**Comment by ericlbarnes** [comment]
Just thinking... 

Wonder if a Theme facade would be beneficial here. Something like: 

```
{{ Theme::get('config.color'); }}
```

Where config is the file inside the theme folder and color would be array key.

**Comment by koomai** [comment]
+1 to that. I think that would be awesome.

**Comment by ericlbarnes** [comment]
Themes can now have a config.php file which just returns a key/value array. 

```
<?php
return array(
    'foo' => 'bar',
);
```

Then in your theme file: 

```
{{ Config::get('theme.foo') }}
```

Which would display `bar` in the browser.
