### ISSUE TITLE
Commenting on posts

### ISSUE THREAD

**Issue by Jeroen-G** [ericlbarnes/wardrobe#32]
I think that one of the basic features of a blog should be the ability to comment on posts. I didn't see any reference to it, so I submitted this issue.

**Comment by rtablada** [comment]
I think that the idea is that wardrobe is pretty minimal. As a feature, I would prefer to see this as an add on wardrobe specific package.

This would allow for greater flexibility and less bloat for blogs that use solutions such as disqus or something else.

**Comment by ericlbarnes** [comment]
Yes I am against having comments in the core as well. I could see a third party building something for this but it isn't something I want to support. As @rtablada mentioned checked out disqus or one of those if you have an immediate need.

**Comment by rtablada** [comment]
Yeah, I just implemented disqus extremely quickly in my own wardrobe blog and I am probably going to write a quick comment package for faster disqus integration.

**Comment by Jeroen-G** [comment]
Al right then, I'll take a look at integrating Disqus.

**Comment by rtablada** [comment]
It's pretty much just throwing in a script tag.
—
