### ISSUE TITLE
Bad configuration issues.

### ISSUE THREAD

**Issue by Medalink** [ericlbarnes/wardrobe#33]
I noticed today that when the app/config/wardrobe.php file has a bad value for per_page it causes an SQL error. I ran into this when I setup my local config files before I ran the install and that did not update the local config file thus leaving a non integer value and causing an SQL error.

Should DbPostRepository()->active() check to make sure the config var is set?

**Comment by ericlbarnes** [comment]
Actually it sounds like the root cause is the installer didn't respect your environment when writing the wardrobe.php file.

**Comment by Medalink** [comment]
Yes that's true too. We should still do a sanity check on the config file value in my opinion, it's better to have an exception then a random SQL query error.

**Comment by Medalink** [comment]
I just did some testing and the install is respecting my environment. The issue was with a bad config or a missing config file.

**Comment by ericlbarnes** [comment]
Yeah I will adjust that for a sanity check.

Here is what I was thinking: https://github.com/ericbarnes/wardrobe/blob/master/app/controllers/InstallController.php#L129

It respects your environment except for actually writing the wardrobe config file.

**Comment by Medalink** [comment]
Ahh yeah you are correct it does not respect it on writing.
