### ISSUE TITLE
Can't publish edited draft

### ISSUE THREAD

**Issue by Jeroen-G** [ericlbarnes/wardrobe#34]
When I publish a post and go back to edit it, I can save the post but not publish it. The post turns into a draft, thereby disappearing from the site. I couldn't find a button or something to change the status to published.

**Comment by rtablada** [comment]
If you click on the button next to the name, it will allow you to change the slug and move between draft and active. Not sure why it would change between states randomly like that...
—

**Comment by ericlbarnes** [comment]
I will try and duplicate this tonight. I can't think of any reason if hand
it would change state like that.

Thanks,
Eric Barnes

On Jun 28, 2013, at 3:14 PM, JeroenG notifications@github.com wrote:

When I publish a post and go back to edit it, I can save the post but not
publish it. The post turns into a draft, thereby disappearing from the
site. I couldn't find a button or something to change the status to
published.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ericbarnes/wardrobe/issues/34
.
