### ISSUE TITLE
RSS Feed Pagination error with no posts

### ISSUE THREAD

**Issue by rtablada** [ericlbarnes/wardrobe#4]
![whoops screen](http://i.imgur.com/tqZ9Fex.png)

In db repository, you call paginate on an empty collection. This seems to have caused the issue. Not sure if you would be able to work around in Wardrobe or it needs to be brought up to @taylorotwell?

**Comment by ericlbarnes** [comment]
I don't think I tested without any posts. Just figured everyone would have at least one. :) 

I will get this fixed.
