### ISSUE TITLE
Visual Install causes file permission issues

### ISSUE THREAD

**Issue by simondavies** [ericlbarnes/wardrobe#40]
When in the set up screen 'localhost/wardrobe/public/install' and then we press the 'Install Database & Continue' i am given a write permissions error. After investigation it is related to the InstallController@postIndex in whcih it has the following code:

```
    Artisan::call('key:generate', array('--env' => App::environment()));
```

Now this obviously want to set a key but as the app.php file is protect its causing the issue, to temporary resolve this i simple commented this out and i managed to get to the next couple of stages.

Before doing this it seems that it is giving it a key automatically, but a closer look is also before running composer install the key is already set and the two versions i have both have the same key - itGxWARLoFR3FxpwAb1ksNlOFhVdJvF0 

So is there a need for the Artisan::call call within the controller?

Once this is completed and i get to the application set up, i enter a site name, theme and number of posts per page etc then press enter but then are greeted with another file permission issue.

This time this is to do with the config/wardrobe.php page as it seems its trying to write the form results to this file within the setWardrobeConfig() in particular the File::get($path), but as this file (wardrobe.php) does not have write permissions it fails.

I tested this and changed the permissions and run it again and had no problems using the application.

**Comment by ericlbarnes** [comment]
I just added setting the permissions on these files to the docs: 
https://github.com/wardrobecms/docs/commit/fffb55cb056259b1c62d7e86a7602318b4382838

Just to confirm after setting the permission everything worked?
