### ISSUE TITLE
Image Uploading

### ISSUE THREAD

**Issue by ericlbarnes** [ericlbarnes/wardrobe#43]
I think it would be ideal to allow image uploading via the content. Basically do it the same way github comments work. You drag and drop the image into the content and it uploads behind the scenes and inserts the markdown image with the correct path.

**Comment by rtablada** [comment]
That'd be sweet. @msurguy might have some image tips.
—

**Comment by ericlbarnes** [comment]
Just found this: - https://github.com/Rovak/InlineAttachment

**Comment by rtablada** [comment]
SEWEEEEET!
—

**Comment by ericlbarnes** [comment]
Started working on this and have it working in the [img-uploading](https://github.com/ericbarnes/wardrobe/tree/img-uploading) branch 

Just need to more error checking in the controller. If any of you feel like testing please do and let me know if you have any troubles. 

![example](http://dl.dropboxusercontent.com/u/2880058/Screenshots/8l.png)

**Comment by rtablada** [comment]
What a beast! Sounds like I'll need to do a pull & merge again soon...

**Comment by simondavies** [comment]
Yeah first used the Git hub version the other day and thought wow, that would be a good idea matches we see what I can test later

**Comment by ericlbarnes** [comment]
Done!

**Comment by rtablada** [comment]
Git pull!
—

**Comment by ericlbarnes** [comment]
Next one :) 

-- Eric

**Comment by simondavies** [comment]
I don't know leave my computer for a while and something happens that makes want to play again. :-) cool will have look later
