### ISSUE TITLE
[Proposal] - Post key/value store

### ISSUE THREAD

**Issue by ericlbarnes** [ericlbarnes/wardrobe#45]
Was thinking about this for a few weeks now but wanted to get some feedback. 

My idea was some place in the post page add the ability for key value storage. So for example the first input would be an autocomplete that looks against existing keys then whatever value you want. 

Let me see if I can give an example: 

```
[input key] [input value]
<button>Add Another</button>
```

Something like that just free form. I think this would allow tons of flexibility in adding all kinds of crazy stuff.

**Comment by rtablada** [comment]
Not sure I understand what leading to...

Within posts you would have this? Or would it be like a CMS "data-type"

**Comment by ericlbarnes** [comment]
I am thinking something sort of like simple YAML: 

   header_img: /path/to/img.png
   link: site.com

So that way you could in theory have custom fields for individual posts.

**Comment by ericlbarnes** [comment]
If that doesn't make sense t will create a mockup over the weekend to better explain. :smile:

**Comment by rtablada** [comment]
Hmmm... I think I get what you are saying now...

**Comment by simondavies** [comment]
To early to think but would be interesting to see your eg

**Comment by Jeroen-G** [comment]
[WordPress](http://codex.wordpress.org/Custom_Fields) has this too for quite a time too I think. Having this in Wardrobe could be awesome. You could use for example if you want to show extra information at specific posts of style them different.

**Comment by ericlbarnes** [comment]
Cool. Wasn't aware wp had this. But yes that is basically the idea. I knew
Jekyll supported fields like this and I have had a few use cases.

Thanks,
Eric Barnes

On Jul 12, 2013, at 2:40 PM, JeroenG notifications@github.com wrote:

WordPress http://codex.wordpress.org/Custom_Fields has this too for quite
a time too I think. Having this in Wardrobe could be awesome. You could use
for example if you want to show extra information at specific posts of
style them different.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ericbarnes/wardrobe/issues/45#issuecomment-20895656
.

**Comment by rtablada** [comment]
Are you thinking to encode json in a text area for storage of the key? Or have a HasMany relation to a key value store table?
—

**Comment by ericlbarnes** [comment]
Haven't thought it all the way through. With a db backend end I think has
many makes the most sense. I am open to suggestions though.

Thanks,
Eric Barnes

On Jul 12, 2013, at 5:58 PM, Ryan Tablada notifications@github.com wrote:

Are you thinking to encode json in a text area for storage of the key? Or
have a HasMany relation to a key value store table?
—
Sent from Mailbox for iPhone

On Fri, Jul 12, 2013 at 5:56 PM, Eric Barnes notifications@github.com
wrote:

> Cool. Wasn't aware wp had this. But yes that is basically the idea. I
> knew
> Jekyll supported fields like this and I have had a few use cases.
> Thanks,
> Eric Barnes
> On Jul 12, 2013, at 2:40 PM, JeroenG notifications@github.com wrote:
> WordPress http://codex.wordpress.org/Custom_Fields has this too for
> quite
> a time too I think. Having this in Wardrobe could be awesome. You could
> use
> for example if you want to show extra information at specific posts of
> style them different.
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/ericbarnes/wardrobe/issues/45#issuecomment-20895656>
> 
> ## .
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ericbarnes/wardrobe/issues/45#issuecomment-20906532

—
Reply to this email directly or view it on
GitHubhttps://github.com/ericbarnes/wardrobe/issues/45#issuecomment-20906648
.

**Comment by Jeroen-G** [comment]
I think that using a table in a db would make it easier to (scan for) use of a single key on multiple posts.

**Comment by aleksblendwerk** [comment]
Only just getting started with Wardrobe and taking it for a first spin but something along these lines to add additional metadata to a post would definitely be a good addition.

You could define the custom keys/fields in the theme's config.php and just display a text area in the post editor that looks like a YAML file with the keys and (for a start, empty) values maybe.

Either way, nice project, keep it going!

**Comment by ryanscherler** [comment]
This would be a great feature for adding to posts. I have been exploring Siteleaf.com as it uses a similar meta key/value for both their pages / posts as well as their settings pages which is a great feature for more global items.

A bit unrelated topic - but besides using static theme 'pages' - will there eventually be a way to edit pages(e.g. make them DB backed) much like posts in Wardrobe? I could see a key / value benefit here too.

**Comment by ericlbarnes** [comment]
Thanks for the feedback. 

Yes I still have this in the plans but I haven't been able to devote much time to the project lately.  Hoping things slow down for me after the holidays. 

I do have some ideas around pages and some more general changes but I can't give a time frame on when I might be able to get that implemented. 

— Eric Barnes

**Comment by ryanscherler** [comment]
I have been working on a side project to learn / get familiar with Laravel (coming from CodeIgniter). I have a basic app with pages that utilize templates and custom fields. It allows a user to define basic field types for a page (no default fields for a page other than title are required, the rest are custom and related to a template). Once I have this farther along I will let you know and maybe it could be of some use? Its a bit more than just adding key/value meta fields to a page, though in the end its really nice to just define what you need at the template level and go from there.
