### ISSUE TITLE
Admin Posts listing page shows active files as Drafts

### ISSUE THREAD

**Issue by sheldonkotyk** [ericlbarnes/wardrobe#51]
It might just be me but even though the post is Active (1) in the DB the posts listings show as Drafts.

Tested with Published and Scheduled posts. Everything else works, looks like it is a display only.

**Comment by ericlbarnes** [comment]
I will check this out. I did make some adjustments with that display a few days ago and probably introduced this then. 

-- Eric Barnes

**Comment by ericlbarnes** [comment]
Sorry that was the wrong issue number in that commit.

**Comment by ericlbarnes** [comment]
That one should fix it. Let me know if for some reason that isn't the case.

**Comment by sheldonkotyk** [comment]
confirmed.
