### ISSUE TITLE
[Request] Commenting system

### ISSUE THREAD

**Issue by dwightwatson** [ericlbarnes/wardrobe#53]
I think a simple commenting system would be a nice addition. If there was interest I might be able to put together a PR to add the basics of the functionality.

**Comment by ericlbarnes** [comment]
I know a disqus package has been created here: 
https://github.com/rtablada/wardrobe-disqus

I am not a big fan of commenting being in the core. I actually think I should start working on a plugin/extension system so things like this could be added if the user so desires.

**Comment by rtablada** [comment]
Thanks eric, I know we had discussed this in the past. I was looking to reference the past issue, but you wrote almost the exact comment I as I had drafted.

**Comment by dwightwatson** [comment]
Ah brilliant, I'll have a look at that package. I wasn't sure if that kind of functionality would be straying too far from the simplicity of Wardrobe. Thanks!
