### ISSUE TITLE
Admin Posts grid in columns based on status

### ISSUE THREAD

**Issue by ericlbarnes** [ericlbarnes/wardrobe#60]
I have had this idea for a while now and figured I should share it and get feedback before I start on it. It will take a pretty large amount of work to accomplish. 

On the posts grid/listing page in admin I have been thinking about changing this to a column type setup like trello/tweetdeck. 

With the headings being "Planning", "In Progress", "Scheduled", "Published", etc. then you could quickly visualize old ideas you've had and what you started but never finished. 

Ideally columns could be created and removed to suit your preference. 

What do you think? Like it or hate it?

**Comment by sheldonkotyk** [comment]
I'd personally rather have a list. It is rare for me to have more than one or two drafts going. Keep it simple please :)

**Comment by beardedbrew** [comment]
Yeah I think you'd be better off with a list and status type indicator.

Then add in something like list.js or a set of sort buttons, to isolate what you want to be looking at.
