### ISSUE TITLE
Saving a post redirects to the Posts page instead of saving and staying in the post.

### ISSUE THREAD

**Issue by jeremykendall** [ericlbarnes/wardrobe#65]
I like to save as I'm writing.  I hate the fact that every time I hit save, it takes me back to the Posts page.  This is kinda related to #64, since it's necessary to save before previewing.  That makes keeping a rhythm pretty difficult, and it's jarring to constantly save, find the post I was working on, click on the post, find my place, and get started again.

Additionally, an "auto-save" feature would be a huge quality-of-life improvement for end users.

**Comment by ericlbarnes** [comment]
Let me break these out: 

>  I hate the fact that every time I hit save, it takes me back to the Posts page

I will fix this for sure. 

> an "auto-save" feature would be a huge quality-of-life improvement for end users.

I need to think about this further. My original goal was to keep the backend portable so the db could be swapped out for flat files, dropbox, etc.  So I am not sure an auto save would really work unless we just db backend only. 

What if it auto saved to local storage? That way when you come back it would be your local save instead of the db save?

**Comment by jeremykendall** [comment]
I'm not sure how auto-save changes the back end requirements.  It would perform the exact same behavior as the current save functionality, just triggered via ajax on a timer.  Am I missing something?

**Comment by rtablada** [comment]
@ericlbarnes I've got some ideas on how to do auto save on the sever if you have the JS chops.

**Comment by ericlbarnes** [comment]
@rtablada Sure lets have it :smile:

**Comment by rtablada** [comment]
When it comes to @ericbarnes and Marionette "impossible takes a week"

**Comment by mpmont** [comment]
I don't miss the auto-save feature. But the save and stay on the same page thingy would be great. One thing I would add to this would be the possibility of having the save button before publishing it or saving it as draft.

This way I could also preview the article. I found myself doing this process:
1. write article.
2. save article
3. go to the article again
4. hit preview.

All this so I could just preview the article on my template. The preview button should be there all along.

**Comment by ericlbarnes** [comment]
This is now implemented in the core repo. Give us a few days and we will get it stable and then get people to use it instead of this one.
