### ISSUE TITLE
[Proposal] Add Parsed Markdown API to Post model

### ISSUE THREAD

**Issue by rtablada** [ericlbarnes/wardrobe#8]
Currently you have to parse the markdown for a post. While this isn't too bad, this puts more logic in the view than is necessary. I was thinking that the post model add a body attribute or something similar which would just be a markdown parsed version of the content so `{{ md($post->body) }}` would just become `{{ $post->body }}`

**Comment by ericlbarnes** [comment]
Yes that is a good idea. Needs to be different than $post->body but that would be useful. Going to think about a new name here.
