### ISSUE TITLE
[Proposal] Clean up scripts and styles for themes

### ISSUE THREAD

**Issue by rtablada** [ericlbarnes/wardrobe#9]
Allow a simple interface to be used in blade to include template css and js files. This is easily done by creating a child of the Laravel HTML Builder that just passes the path through the theme_path helper before passing this on to the traditional HTMLBuilder parent.

This removes logic from the view `{{ theme_path('css/style.css') }}` inside of a large link tag then just becomes `HTML::style('css/style.css')`. A different thought would be to create a Theme helper class that would allow syntax like `Theme::style('css/style.css')` this may be a bit more maintainable as it would still allow Laravel devs to use the HTML facade per usual while giving them a designer friendly API for themes!

**Comment by ericlbarnes** [comment]
I am actually on the fence with that. I actually prefer the more expressive: 

```
<link href="/{{ theme_path('css/style.css') }}" rel="stylesheet" media="screen">
```

I feel it's more immediately recognizable for people outside the laravel world.

**Comment by rtablada** [comment]
Maybe I'll change it from a core request to a Theme helper that allows the extended HTML builder as well as a `Theme::path($relURL)` that would allow it to replace the theme_path() helper.
